spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  devtools:
    restart:
      enabled: true
  datasource:
    stg:
      url: jdbc:mysql://127.0.0.1:3306/stg
      username: hoge
      password: pass
    prod:
      url: jdbc:mysql://127.0.0.1:3306/prod
      username: hoge
      password: pass
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org:
      ehcache: debug
      hibernate:
        SQL: debug
